import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, RedirectToSignIn, ClerkLoading } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          {/* Loading state while Clerk checks authentication */}
          <ClerkLoading>
            <div>Loading...</div>
          </ClerkLoading>

          <SignedIn>
            {children} {/* Render protected content if signed in */}
          </SignedIn>

          <SignedOut>
            <RedirectToSignIn /> {/* Redirect to Clerk sign-in page */}
          </SignedOut>
        </ClerkProvider>
      </body>
    </html>
  );
}
